using Npgsql;

public class WordCountRepository
{
    private readonly string _connectionString;
   
    public WordCountRepository(string connectionString)
    {
        _connectionString = connectionString;
    }
    
    public void SaveWordCount(string fileName, int wordCount)
    {
        try
        {
            using var connect = new NpgsqlConnection(_connectionString);
            connect.Open();

            // Use MAX(id)+1 to simulate auto-increment
            using var cmd = connect.CreateCommand();
            cmd.CommandText = @"
                INSERT INTO Words (id, filename, wordcount)
                SELECT COALESCE(MAX(id), 0) + 1, @filename, @wordcount
                FROM Words;
            ";
            cmd.Parameters.AddWithValue("filename", fileName);
            cmd.Parameters.AddWithValue("wordcount", wordCount);

            cmd.ExecuteNonQuery();
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException("Error saving word count to the database. Verify that WORDCOUNTER_CONNECTION_STRING points to a reachable database with valid credentials.", ex);
        }
    }
    // this code was generated by copilot studio
    public IEnumerable<WordCountRecord> GetAllWordCounts()
    {
        var wordCounts = new List<WordCountRecord>();
        try
        {
            using var connect = new NpgsqlConnection(_connectionString);
            connect.Open();

            using var cmd = connect.CreateCommand();
            cmd.CommandText = "SELECT id, filename, wordcount FROM Words;";

            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                wordCounts.Add(new WordCountRecord
                {
                    Id = reader.GetInt32(0),
                    FileName = reader.GetString(1),
                    WordCount = reader.GetInt32(2)
                });
            }
        }
        catch (Exception ex)
        {
            // Log or handle the exception as needed
            throw new InvalidOperationException("Error retrieving word counts from database.", ex);
        }
        return wordCounts;
    }
    
}

// this code was generated by copilot studio
public class WordCountRecord
{
    public int Id { get; set; }
    public string FileName { get; set; } = string.Empty;
    public int WordCount { get; set; }
}
